export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

//DAHSBOARD REDUCER
export const DASHBOARD_PROJECT_LIST_GRID = "DASHBOARD_PROJECT_LIST_GRID";

//PROJECT REDUCER
export const GET_PROJECT_DETAILS = "GET_PROJECT_DETAILS";
