export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REFRESH_TOKEN_GENARATED = "REFRESH_TOKEN_GENARATED";
export const ACCESS_TOKEN_ERROR = "ACCESS_TOKEN_ERROR";
export const ACCESS_TOKEN_SUCCESS = "ACCESS_TOKEN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const RESET_LINK_SEND = "RESET_LINK_SEND";
export const RESET_LINK_SEND_ERROR = "RESET_LINK_SEND_ERROR";
export const PASSWORD_CHANGE = "PASSWORD_CHANGE";
export const PASSWORD_CHANGE_ERROR = "PASSWORD_CHANGE_ERROR";

//PROFILE REDUCER
export const AUTH_USER_LOAD = "AUTH_USER_LOAD";
export const AUTH_USER_LOAD_ERROR = "AUTH_USER_LOAD_ERROR";
export const PROFILE_UPDATE = "PROFILE_UPDATE";
export const PROFILE_UPDATE_ERROR = "PROFILE_UPDATE_ERROR";

//DAHSBOARD REDUCER
export const DASHBOARD_PROJECT_LIST_GRID = "DASHBOARD_PROJECT_LIST_GRID";
export const SIDEBAR_TOGGLE = "SIDEBAR_TOGGLE";
export const CLIENT_LIST_LOAD = "CLIENT_LIST_LOAD";
export const MANAGER_LIST_LOAD = "MANAGER_LIST_LOAD";
export const DEVELOPER_LIST_LOAD = "DEVELOPER_LIST_LOAD";
export const SET_ROLE = "SET_ROLE";
export const APPROVED_PROJECT_LOAD = "APPROVED_PROJECT_LOAD";
export const APPROVED_PROJECT_LOAD_ERROR = "APPROVED_PROJECT_LOAD_ERROR";

//PROJECT REDUCER
export const GET_PROJECT_DETAILS = "GET_PROJECT_DETAILS";
export const GET_INVITED_PROJECT_DETAILS = "GET_INVITED_PROJECT_DETAILS";
export const PROJECT_INVITATION_SUCCESS = "PROJECT_INVITATION_SUCCESS";
export const PROJECT_INVITATION_ERROR = "PROJECT_INVITATION_ERROR";
export const ACCOUNT_CREATE_SUCCESS = "ACCOUNT_CREATE_SUCCESS";
export const ACCOUNT_CREATE_ERROR = "ACCOUNT_CREATE_ERROR";
export const PROJECT_CREATE_SUCCESS = "PROJECT_CREATE_SUCCESS";
export const PROJECT_CREATE_ERROR = "PROJECT_CREATE_ERROR";
export const FETCH_DASHBOARD_PROJECT = "FETCH_DASHBOARD_PROJECT";
export const FETCH_DASHBOARD_PROJECT_ERROR = "FETCH_DASHBOARD_PROJECT_ERROR";
export const ADD_FAVORITE_PROJECT = "ADD_FAVORITE_PROJECT";
export const REMOVE_FAVORITE_PROJECT = "REMOVE_FAVORITE_PROJECT";
export const TASK_ADDED = "TASK_ADDED";
export const TASK_ADDED_ERROR = "TASK_ADDED_ERROR";
export const GET_STEP = "GET_STEP";
export const GET_STEP_ERROR = "GET_STEP_ERROR";
export const ADD_COLLECTION_SUCCESS = "ADD_COLLECTION_SUCCESS";
export const ADD_COLLECTION_ERROR = "ADD_COLLECTION_ERROR";
export const COLLECTION_NEXT = "COLLECTION_NEXT";
export const COLLECTION_PREV = "COLLECTION_PREV";
export const COLLECTION_INDEX = "COLLECTION_INDEX";
export const STEP_APPROVED = "STEP_APPROVED";
export const STEP_APPROVE_ERROR = "STEP_APPROVE_ERROR";
export const PROJECT_ACCEPT_EXISTING_USER = "PROJECT_ACCEPT_EXISTING_USER";
export const PROJECT_ACCEPT_EXISTING_USER_ERROR =
  "PROJECT_ACCEPT_EXISTING_USER_ERROR";
export const REVIEW_ADDED = "REVIEW_ADDED";
export const REVIEW_ADDED_ERROR = "REVIEW_ADDED_ERROR";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR";

//REDIRECT REDUCER
export const REDIRECT_TO_DASHBOARD = "REDIRECT_TO_DASHBOARD";
export const REDIRECT_TO_ROOT = "REDIRECT_TO_ROOT";
