export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REFRESH_TOKEN_GENARATED = "REFRESH_TOKEN_GENARATED";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

//DAHSBOARD REDUCER
export const DASHBOARD_PROJECT_LIST_GRID = "DASHBOARD_PROJECT_LIST_GRID";
export const SIDEBAR_TOGGLE = "SIDEBAR_TOGGLE";

//PROJECT REDUCER
export const GET_PROJECT_DETAILS = "GET_PROJECT_DETAILS";
export const GET_INVITED_PROJECT_DETAILS = "GET_INVITED_PROJECT_DETAILS";
export const PROJECT_INVITATION_SUCCESS = "PROJECT_INVITATION_SUCCESS";
export const PROJECT_INVITATION_ERROR = "PROJECT_INVITATION_ERROR";
